SELECT * FROM COMTNLOGINPOLICY
;

SELECT * FROM comtnloginpolicy
;

SELECT EMPLYR_ID, IP_INFO, DPLCT_PERM_AT, LMTT_AT, FRST_REGISTER_ID, FRST_REGIST_PNTTM, LAST_UPDUSR_ID, LAST_UPDT_PNTTM
FROM com.comtnloginpolicy;

SELECT /* 공통표준단어Mapper.select공통표준단어 */
       EMPLYR_ID
     , IP_INFO
     , DPLCT_PERM_AT
     , LMTT_AT
     , FRST_REGISTER_ID
     , FRST_REGIST_PNTTM
     , LAST_UPDUSR_ID
     , LAST_UPDT_PNTTM
  FROM COM.COMTNLOGINPOLICY;

INSERT INTO com.comtnloginpolicy
(EMPLYR_ID, IP_INFO, DPLCT_PERM_AT, LMTT_AT, FRST_REGISTER_ID, FRST_REGIST_PNTTM, LAST_UPDUSR_ID, LAST_UPDT_PNTTM)
VALUES('', '', '', '', NULL, NULL, NULL, NULL);

INSERT INTO com.comtnloginpolicy
(EMPLYR_ID, IP_INFO, DPLCT_PERM_AT, LMTT_AT, FRST_REGISTER_ID, FRST_REGIST_PNTTM, LAST_UPDUSR_ID, LAST_UPDT_PNTTM)
VALUES(NULL, '', '', '', NULL, NULL, NULL, NULL);

UPDATE com.comtnloginpolicy
SET IP_INFO='', DPLCT_PERM_AT='', LMTT_AT='', FRST_REGISTER_ID=NULL, FRST_REGIST_PNTTM=NULL, LAST_UPDUSR_ID=NULL, LAST_UPDT_PNTTM=NULL
WHERE EMPLYR_ID='';

DELETE FROM com.comtnloginpolicy
WHERE EMPLYR_ID='';

MERGE INTO com.comtnloginpolicy AS tgt
USING SOURCE_TABLE AS src
ON (tgt.EMPLYR_ID=src.EMPLYR_ID)
WHEN MATCHED
THEN UPDATE SET
tgt.IP_INFO=src.IP_INFO, tgt.DPLCT_PERM_AT=src.DPLCT_PERM_AT, tgt.LMTT_AT=src.LMTT_AT, tgt.FRST_REGISTER_ID=src.FRST_REGISTER_ID, tgt.FRST_REGIST_PNTTM=src.FRST_REGIST_PNTTM, tgt.LAST_UPDUSR_ID=src.LAST_UPDUSR_ID, tgt.LAST_UPDT_PNTTM=src.LAST_UPDT_PNTTM
WHEN NOT MATCHED
THEN INSERT (EMPLYR_ID, IP_INFO, DPLCT_PERM_AT, LMTT_AT, FRST_REGISTER_ID, FRST_REGIST_PNTTM, LAST_UPDUSR_ID, LAST_UPDT_PNTTM)
VALUES (src.EMPLYR_ID, src.IP_INFO, src.DPLCT_PERM_AT, src.LMTT_AT, src.FRST_REGISTER_ID, src.FRST_REGIST_PNTTM, src.LAST_UPDUSR_ID, src.LAST_UPDT_PNTTM);
