SELECT * FROM COMTNLOGINPOLICY
;

SELECT EMPLYR_ID, IP_INFO, DPLCT_PERM_AT, LMTT_AT, FRST_REGISTER_ID, FRST_REGIST_PNTTM, LAST_UPDUSR_ID, LAST_UPDT_PNTTM
FROM COMTNLOGINPOLICY;

SELECT /* Maper.select */
       T1.EMPLYR_ID /* 업무사용자ID */
     , IP_INFO
     , DPLCT_PERM_AT
     , LMTT_AT
     , FRST_REGISTER_ID
     , FRST_REGIST_PNTTM
     , LAST_UPDUSR_ID
     , LAST_UPDT_PNTTM
  FROM COMTNLOGINPOLICY T1 /* 로그인정책 */
;

INSERT INTO COMTNLOGINPOLICY
(EMPLYR_ID, IP_INFO, DPLCT_PERM_AT, LMTT_AT, FRST_REGISTER_ID, FRST_REGIST_PNTTM, LAST_UPDUSR_ID, LAST_UPDT_PNTTM)
VALUES('', '', '', '', NULL, NULL, NULL, NULL);

UPDATE com.comtnloginpolicy
SET IP_INFO='', DPLCT_PERM_AT='', LMTT_AT='', FRST_REGISTER_ID=NULL, FRST_REGIST_PNTTM=NULL, LAST_UPDUSR_ID=NULL, LAST_UPDT_PNTTM=NULL
WHERE EMPLYR_ID='';

DELETE FROM com.comtnloginpolicy
WHERE EMPLYR_ID='';

MERGE INTO com.comtnloginpolicy AS tgt
USING SOURCE_TABLE AS src
ON (tgt.EMPLYR_ID=src.EMPLYR_ID)
WHEN MATCHED
THEN UPDATE SET
tgt.IP_INFO=src.IP_INFO, tgt.DPLCT_PERM_AT=src.DPLCT_PERM_AT, tgt.LMTT_AT=src.LMTT_AT, tgt.FRST_REGISTER_ID=src.FRST_REGISTER_ID, tgt.FRST_REGIST_PNTTM=src.FRST_REGIST_PNTTM, tgt.LAST_UPDUSR_ID=src.LAST_UPDUSR_ID, tgt.LAST_UPDT_PNTTM=src.LAST_UPDT_PNTTM
WHEN NOT MATCHED
THEN INSERT (EMPLYR_ID, IP_INFO, DPLCT_PERM_AT, LMTT_AT, FRST_REGISTER_ID, FRST_REGIST_PNTTM, LAST_UPDUSR_ID, LAST_UPDT_PNTTM)
VALUES (src.EMPLYR_ID, src.IP_INFO, src.DPLCT_PERM_AT, src.LMTT_AT, src.FRST_REGISTER_ID, src.FRST_REGIST_PNTTM, src.LAST_UPDUSR_ID, src.LAST_UPDT_PNTTM);

WITH CTE_NAME AS (
SELECT /* Mapper.select */
--      CONCAT('     , A.', A.COLUMN_NAME, ' /* ', A.COLUMN_COMMENT, ' */') AS SQL1
-- 
       CONCAT(LOWER(SUBSTRING_INDEX(A.COLUMN_NAME, '_', 1)), UPPER(LEFT(SUBSTRING_INDEX(A.COLUMN_NAME, '_', -1), 1)), LOWER(SUBSTRING(SUBSTRING_INDEX(A.COLUMN_NAME, '_', -1), 2))) AS CAMEL_CASE_COLUMN
--      , A.COLUMN_NAME
--      , A.IS_NULLABLE
--      , A.DATA_TYPE
--      , A.CHARACTER_MAXIMUM_LENGTH
--      , A.COLUMN_KEY
--      , A.COLUMN_COMMENT
-- 
     , A.*
  FROM INFORMATION_SCHEMA.COLUMNS A
 WHERE 1 = 1
   AND A.TABLE_SCHEMA = 'com'
   AND A.TABLE_NAME = 'comtnloginpolicy'
   AND A.TABLE_NAME = 'COMTNLOGINPOLICY'
 ORDER BY A.TABLE_CATALOG, A.TABLE_SCHEMA, A.TABLE_NAME, A.ORDINAL_POSITION
)
SELECT
       CONCAT('     , A.', A.COLUMN_NAME, ' /* ', A.COLUMN_COMMENT, ' */') AS SQL1
     , CONCAT('private String ', A.CAMEL_CASE_COLUMN, ';') AS VO
     , CONCAT('#{', A.CAMEL_CASE_COLUMN, '}', ' /* ', A.COLUMN_COMMENT, ' */') AS Mapper
     , A.CAMEL_CASE_COLUMN
     , A.COLUMN_NAME
     , A.IS_NULLABLE
     , A.DATA_TYPE
     , A.CHARACTER_MAXIMUM_LENGTH
     , A.COLUMN_KEY
     , A.COLUMN_COMMENT
-- 
     , A.*
  FROM CTE_NAME A
;

CREATE OR REPLACE SEQUENCE SEQ_COMTNLOGINPOLICY INCREMENT BY 1 MINVALUE 1 NOCYCLE 
;

CREATE SEQUENCE SEQ_COMTNLOGINPOLICY;

SELECT LASTVAL(SEQ_COMTNLOGINPOLICY)
;

SELECT NEXTVAL(SEQ_COMTNLOGINPOLICY)
;

SELECT LASTVAL(SEQ_COMTNLOGINPOLICY2)
;

SELECT NEXTVAL(SEQ_COMTNLOGINPOLICY2)
;

SELECT LASTVAL(SEQ_COMTNLOGINPOLICY3)
;

SELECT NEXTVAL(SEQ_COMTNLOGINPOLICY3)
;
